title: Fizz Buzz AI
email: willettisaak@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Fizz Buzz has been described as the hardest problem in computer science.
  With Fizz Buzz AI an attempt is being made to solve this unsolvable problem
  with the most advanced methods.
baseurl: "/fizz-buzz-ai" # the subpath of your site, e.g. /blog
url: "https://pickles-bread-and-butter.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pickles-bread-and-butter

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
